config/routes.rb
Nhl13::Application.routes.draw do
  match '/players/recent' => 'players#recent'

  resources :players
  resources :teams

  root :to => 'teams#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  has_many :salary_histories

  attr_accessible :check_position, :defense_rebound, :hand_quick, :handed, :name, :overall, :player_type, :position, :ps3_auction, :ps3_bin, :salary, :shot_low, :skate_high, :sotw, :true_overall, :xbox_auction, :xbox_bin, :team, :team_id
  
  def update_for_save(request)
    update_overall
    create_salary_history(request)
  end

private 
  def update_overall
    average = (self.check_position.to_f + self.defense_rebound.to_f + self.hand_quick.to_f + self.shot_low.to_f + self.skate_high.to_f) / 5.0

    self.overall = average.round.to_i
    self.true_overall = average

  end

  def create_salary_history(request)
    self.salary_histories << SalaryHistory.new({ player_id: self,
                                                  ps3_bin: self.ps3_bin,
                                                  ps3_auction: self.ps3_auction,
                                                  xbox_bin: self.xbox_bin,
                                                  xbox_auction: self.xbox_auction,
                                                  ip_address: request.remote_ip})
  end
end

app/models/salary_history.rb
class SalaryHistory < ActiveRecord::Base
  belongs_to :player
  attr_accessible :ip_address, :ps3_auction, :ps3_bin, :xbox_auction, :xbox_bin, :player_id
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  before_filter :set_show_deletes

  def index
    @players = Player.all(:include => :team)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players.as_json(:include=>[:team]) }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])
    @player.update_for_save(request)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    @player.assign_attributes(params[:player])
    @player.update_for_save(request)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  def recent
    @players = Player.includes(:team).where('updated_at > ?', 1.day.ago).order('updated_at desc')


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players.as_json(:include=>[:team]) }
    end
  end

protected
  def set_show_deletes
    @show_deletes = true unless params[:show_deletes].nil?
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all()


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams.as_json() }
    end
  end

  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nhl13" %></title>
    <%= csrf_meta_tags %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Nhl13</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Recent Updates", "/players/recent"  %></li>
              <li><%= link_to "Teams", "/teams"  %></li>
              <li><%= link_to "Players", "/players"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= yield %>
        </div>
      </div><!--/row-->

      <br />
      <footer>
        <p>made by mendicant</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.select :team_id, Team.all.collect {|team| [team.name, team.id]} %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sotw, 'SOTW' %>
    <%= f.check_box :sotw %>
  </div>
  <div class="field">
    <%= f.label :position, 'POS' %>
    <%= f.select :position, ['C', 'LW', 'RW', 'LD', 'RD', 'G'] %>
  </div>
  <div class="field">
    <%= f.label :player_type, 'Type' %>
    <%= f.select :player_type, ['SNP', 'PLY', 'PWF', 'TWF', 'GRN', 'OFD', 'DFD', 'TWD', 'BUT', 'HYB', 'STD'] %>
  </div>
  <div class="field">
    <%= f.label :handed %>
    <%= f.select :handed, ['Left', 'Right'] %>
  </div>
  <div class="field">
    <%= f.label :ps3_bin, 'PS3 BIN' %>
    <%= f.number_field :ps3_bin %>
  </div>
  <div class="field">
    <%= f.label :ps3_auction, 'PS3 AUC' %>
    <%= f.number_field :ps3_auction %>
  </div>
  <div class="field">
    <%= f.label :xbox_bin, 'XBox BIN' %>
    <%= f.number_field :xbox_bin %>
  </div>
  <div class="field">
    <%= f.label :xbox_auction, 'XBox AUC' %>
    <%= f.number_field :xbox_auction %>
  </div>
  <div class="field">
    <%= f.label :skate_high, 'SKT/HGH' %>
    <%= f.number_field :skate_high %>
  </div>
  <div class="field">
    <%= f.label :shot_low, 'SHT/LOW' %>
    <%= f.number_field :shot_low %>
  </div>
  <div class="field">
    <%= f.label :hand_quick, 'HND/QCK' %>
    <%= f.number_field :hand_quick %>
  </div>
  <div class="field">
    <%= f.label :check_position, 'CHK/POS' %>
    <%= f.number_field :check_position %>
  </div>
  <div class="field">
    <%= f.label :defense_rebound, 'DEF/RBD' %>
    <%= f.number_field :defense_rebound %>
  </div>
  <div class="field">
    <%= f.label :salary %>
    <%= f.text_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_players_table.html.erb
<table id="players-table">
  <thead>
    <tr>
      <th class='filter-select'>Team</th>
      <th>Name</th>
      <th class='filter-select'>SOTW</th>
      <th class='filter-select'>POS</th>
      <th class='filter-select'>Type</th>
      <th class='filter-select'>Hand</th>
      <th>PS3 BIN</th>
      <th>PS3 AUC</th>
      <th>XBox BIN</th>
      <th>XBox AUC</th>
      <th>SKT/HGH</th>
      <th>SHT/LOW</th>
      <th>HND/QCK</th>
      <th>CHK/POS</th>
      <th>DEF/RBD</th>
      <th>OVR</th>
      <th>True OVR</th>
      <th>Salary</th>
      <th>Last Update</th>
      <th></th>
      <th></th>
      <% if @show_deletes %>
      <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% players.each do |player| %>
      <tr>
        <td><%= player.team.name %></td>
        <td><%= player.name %></td>
        <td><%= player.sotw %></td>
        <td><%= player.position %></td>
        <td><%= player.player_type %></td>
        <td><%= player.handed %></td>
        <td class="ps3"><%= player.ps3_bin %></td>
        <td class="ps3"><%= player.ps3_auction %></td>
        <td class="xbox"><%= player.xbox_bin %></td>
        <td class="xbox"><%= player.xbox_auction %></td>
        <td><%= player.skate_high %></td>
        <td><%= player.shot_low %></td>
        <td><%= player.hand_quick %></td>
        <td><%= player.check_position %></td>
        <td><%= player.defense_rebound %></td>
        <td><%= player.overall %></td>
        <td><%= player.true_overall %></td>
        <td><%= player.salary %></td>
        <td><%= player.updated_at.strftime("%Y-%m-%d %H:%M") %> EST</td>

        <td><%= link_to 'Show', player_path(player), :class => 'btn' %></td>
        <td><%= link_to 'Edit', edit_player_path(player), :class => 'btn' %></td>
        <% if @show_deletes %>
          <td><%= link_to 'Delete', player_path(player), { :method => :delete, :confirm => "Are you sure you want to delete #{player.name}" } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<%= render :partial => 'players_table', :locals => {:players => @players } %>
<br/>

<%= link_to 'New Player', new_player_path, :class => 'btn' %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/recent.html.erb
<h1>Recently Updated Players</h1>

<%= render :partial => 'players_table', :locals => {:players => @players } %>
<br/>

<%= link_to 'New Player', new_player_path, :class => 'btn'%>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<table class="show_player_table">
  <tr>
    <td>
      <b>Team:</b>
    </td>
    <td>
      <%= @player.team.name %>
    </td>
    <td>
      <b>Name:</b>
    </td>
    <td>
      <%= @player.name %>
    </td>
  </tr>
  <tr>
    <td>
      <b>SOTW:</b>
    </td>
    <td>
      <%= @player.sotw %>
    </td>
    <td>
      <b>Handed:</b>
    </td>
    <td>
      <%= @player.handed %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Ps3 BIN:</b>
    </td>
    <td>
      <%= @player.ps3_bin %>
    </td>
    <td>
      <b>Ps3 Auction:</b>
    </td>
    <td>
      <%= @player.ps3_auction %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Xbox BIN:</b>
    </td>
    <td>
      <%= @player.xbox_bin %>
    </td>
    <td>
      <b>Xbox Auction:</b>
    </td>
    <td>
      <%= @player.xbox_auction %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Skate/High:</b>
    </td>
    <td>
      <%= @player.skate_high %>
    </td>
    <td>
      <b>Shot/Low:</b>
    </td>
    <td>
      <%= @player.shot_low %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Hand/Quick:</b>
    </td>
    <td>
      <%= @player.hand_quick %>
    </td>
    <td>
      <b>Check/Position:</b>
    </td>
    <td>
      <%= @player.check_position %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Defense/Rebound:</b>
    </td>
    <td>
      <%= @player.defense_rebound %>
    </td>
    <td>
      <b>Position:</b>
    </td>
    <td>
      <%= @player.position %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Overall:</b>
    </td>
    <td>
      <%= @player.overall %>
    </td>
    <td>
      <b>True Overall:</b>
    </td>
    <td>
      <%= @player.true_overall %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Player Type:</b>
    </td>
    <td>
      <%= @player.player_type %>
    </td>
    <td>
      <b>Salary:</b>
    </td>
    <td>
      <%= @player.salary %>
    </td>
  </tr>
</table>
<br />
<br />

<table class="show_history_table">
  <tr>
    <th>PS3 BIN</th>
    <th>PS3 AUC</th>
    <th>XBox BIN</th>
    <th>XBox AUC</th>
    <th>Date</th>
    <% if @show_deletes %>
      <th></th>
    <% end %>
  </tr>
  <% @player.salary_histories.each do |salary| %>
    <tr>
      <td><%= salary.ps3_bin %></td>
      <td><%= salary.ps3_auction %></td>
      <td><%= salary.xbox_bin %></td>
      <td><%= salary.xbox_auction %></td>
      <td><%= salary.created_at.strftime("%Y-%m-%d %H:%M") %></td>
      <% if @show_deletes %>
        <td>Delete goes here</td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />
<%= link_to 'Edit', edit_player_path(@player), :class => 'btn' %> |
<%= link_to 'Back', players_path, :class => 'btn' %>